"""Real Alembic upgrade/check/downgrade coverage against a live Postgres —
previously verified only by hand ("in this sandbox, against a real local
Postgres instance"), per CLAUDE.md's own Alembic section, but never
automated: a bad autogenerated revision in a future db/models.py change
would only surface on a real deployment, not in CI.

Skipped (not failed) unless DATABASE_URL is set, same "opt-in when the
infra it needs isn't available" convention as tests_live/ — but unlike
that directory, this file lives inside tests/ since a local/CI Postgres
instance isn't a live external scrape target (no third-party site, no
flakiness risk that convention exists to avoid), it's ordinary test infra.
`python -m pytest tests/` (this repo's own documented, no-network command)
is unaffected when DATABASE_URL isn't set — the same as any contributor's
local run without Postgres configured. CI wires DATABASE_URL for a single,
narrowly-scoped extra step (see .github/workflows/ci.yml) rather than for
the whole test suite, since many existing tests assert on DATABASE_URL
being *unset* and already isolate it per-test via pop/restore — setting it
process-wide for the entire pytest run would risk interfering with those.
"""
import os
import unittest

DATABASE_URL = os.environ.get("DATABASE_URL")


@unittest.skipUnless(DATABASE_URL, "DATABASE_URL not set — see this module's own docstring")
class AlembicMigrationTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        from alembic.config import Config

        from db.models import get_engine, metadata

        cls.engine = get_engine(DATABASE_URL)
        repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        cls.cfg = Config(os.path.join(repo_root, "alembic.ini"))
        cls.cfg.set_main_option("script_location", os.path.join(repo_root, "migrations"))
        cls.metadata = metadata

    def setUp(self) -> None:
        # Clean slate before every test — this app's own tables plus
        # Alembic's own bookkeeping table, so a prior failed run (or a
        # developer re-running this file against a persistent local
        # Postgres, not just CI's fresh-per-job container) can't leave
        # stale state that masks a real failure.
        from sqlalchemy import text

        self.metadata.drop_all(self.engine)
        with self.engine.begin() as conn:
            conn.execute(text("DROP TABLE IF EXISTS alembic_version"))

    def tearDown(self) -> None:
        from sqlalchemy import text

        self.metadata.drop_all(self.engine)
        with self.engine.begin() as conn:
            conn.execute(text("DROP TABLE IF EXISTS alembic_version"))

    def test_upgrade_head_creates_every_table(self) -> None:
        from alembic import command
        from sqlalchemy import inspect

        command.upgrade(self.cfg, "head")

        inspector = inspect(self.engine)
        actual_tables = set(inspector.get_table_names())
        expected_tables = set(self.metadata.tables.keys())
        self.assertEqual(expected_tables - actual_tables, set())

    def test_upgrade_head_then_check_reports_no_drift(self) -> None:
        # alembic check raises AutogenerateDiffsDetected if the live schema
        # and db/models.py's metadata have diverged — the exact scenario a
        # hand-edited db/models.py with a forgotten/wrong revision would
        # produce. A clean run (no exception) is the pass condition.
        from alembic import command

        command.upgrade(self.cfg, "head")
        command.check(self.cfg)  # raises on drift; the test fails via the raised exception

    def test_downgrade_base_removes_every_table(self) -> None:
        from alembic import command
        from sqlalchemy import inspect

        command.upgrade(self.cfg, "head")
        command.downgrade(self.cfg, "base")

        inspector = inspect(self.engine)
        actual_tables = set(inspector.get_table_names())
        app_tables = set(self.metadata.tables.keys())
        self.assertEqual(app_tables & actual_tables, set())

    def test_stamp_head_on_a_pre_existing_schema_matches_upgrade_head(self) -> None:
        # The documented existing-deployment path: a database that already
        # has every table (created via metadata.create_all(), the same way
        # sme_ema_pipeline.py/screener_pipeline.py's --setup-db do) should
        # be stampable as "already at head" with zero drift afterward —
        # exactly db.models.stamp_alembic_head's own contract.
        from alembic import command

        from db.models import stamp_alembic_head

        self.metadata.create_all(self.engine)
        stamp_alembic_head()
        command.check(self.cfg)  # raises on drift


if __name__ == "__main__":
    unittest.main()
