"""add eod price store and corporate actions tables

Revision ID: 684c8a31e7e0
Revises: 0001
Create Date: 2026-08-02 10:16:33.759194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684c8a31e7e0'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('purpose_raw', sa.String(length=300), nullable=False),
    sa.Column('price_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ex_date', 'purpose_raw', name='uq_corp_actions_sym_ex_purpose')
    )
    op.create_index('idx_corp_actions_symbol', 'corporate_actions', ['symbol'], unique=False)
    op.create_table('mf_nav_daily',
    sa.Column('scheme_code', sa.String(length=12), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('scheme_name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('scheme_code', 'nav_date')
    )
    op.create_table('prices_daily',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover_lacs', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('delivery_qty', sa.BigInteger(), nullable=True),
    sa.Column('delivery_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'trade_date')
    )
    op.create_index('idx_prices_daily_date', 'prices_daily', ['trade_date'], unique=False)
    op.create_table('securities',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities')
    op.drop_index('idx_prices_daily_date', table_name='prices_daily')
    op.drop_table('prices_daily')
    op.drop_table('mf_nav_daily')
    op.drop_index('idx_corp_actions_symbol', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
