"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-07-26 17:17:26.562527

Autogenerated from db/models.py::metadata (`alembic revision --autogenerate`)
against an empty database — this is every table this app already relies on
(the same 11 tables db/schema.sql hand-declares), not a new schema change.

IMPORTANT for existing deployments: this repo managed its schema by hand
before this migration existed (db/schema.sql's own `CREATE TABLE IF NOT
EXISTS` + `ALTER TABLE ... ADD COLUMN IF NOT EXISTS` guards, applied
manually — see CLAUDE.md's "Route module extraction" era docs, or really
any deployment that already has these tables). Running `alembic upgrade
head` against a database that already has this schema will fail on the
first `CREATE TABLE` (the table already exists). Existing deployments
should run `alembic stamp head` instead — this records "already at 0001"
without executing any DDL. Only a genuinely fresh, empty database should
run `alembic upgrade head` against this revision.

From here on, schema changes should be authored as new Alembic revisions
(`alembic revision --autogenerate -m "..."` after editing db/models.py) —
see CLAUDE.md's "Schema migrations" section for the full workflow and why
db/schema.sql is being kept around as a frozen reference rather than
deleted outright.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_magic_links_email', 'magic_links', ['email'], unique=False)
    op.create_table('mf_holdings_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('fund', sa.String(length=200), nullable=False),
    sa.Column('holding_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of_date', 'fund', name='uq_mf_holdings_history_symbol_date_fund')
    )
    op.create_index('idx_mf_holdings_history_symbol', 'mf_holdings_history', ['symbol'], unique=False)
    op.create_table('screener_stocks',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=5), nullable=True),
    sa.Column('nse_industry', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('avg_volume_10d', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ema_trend', sa.String(length=10), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('idx_screener_stocks_industry', 'screener_stocks', ['nse_industry'], unique=False)
    op.create_index('idx_screener_stocks_sector', 'screener_stocks', ['sector'], unique=False)
    op.create_table('sme_stocks',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(length=5), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('avg_volume_20d', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('avg_turnover_20d', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('tier', sa.String(length=10), server_default=sa.text("'free'"), nullable=False),
    sa.CheckConstraint("tier IN ('free', 'pro')", name='ck_users_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verdict_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('verdict_date', sa.Date(), nullable=False),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('signal_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'verdict_date', name='uq_verdict_history_symbol_date')
    )
    op.create_index('idx_verdict_history_symbol', 'verdict_history', ['symbol'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_user', 'api_keys', ['user_id'], unique=False)
    op.create_table('ema_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('volume_spike', sa.Boolean(), nullable=True),
    sa.Column('cross_type', sa.String(length=10), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['sme_stocks.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_ema_signals_symbol_date')
    )
    op.create_index('idx_ema_signals_cross', 'ema_signals', ['cross_type'], unique=False)
    op.create_index('idx_ema_signals_date', 'ema_signals', ['trade_date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=5), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('shares', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('bought_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint('(client_id IS NULL) <> (user_id IS NULL)', name='ck_positions_exactly_one_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'symbol', name='uq_positions_client_symbol'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_positions_user_symbol')
    )
    op.create_index('idx_positions_client', 'positions', ['client_id'], unique=False)
    op.create_index('idx_positions_user', 'positions', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=5), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.CheckConstraint('(client_id IS NULL) <> (user_id IS NULL)', name='ck_watchlist_exactly_one_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'symbol', name='uq_watchlist_client_symbol'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    op.create_index('idx_watchlist_client', 'watchlist_items', ['client_id'], unique=False)
    op.create_index('idx_watchlist_user', 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_user', table_name='watchlist_items')
    op.drop_index('idx_watchlist_client', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_positions_user', table_name='positions')
    op.drop_index('idx_positions_client', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_ema_signals_date', table_name='ema_signals')
    op.drop_index('idx_ema_signals_cross', table_name='ema_signals')
    op.drop_table('ema_signals')
    op.drop_index('idx_api_keys_user', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_verdict_history_symbol', table_name='verdict_history')
    op.drop_table('verdict_history')
    op.drop_table('users')
    op.drop_table('sme_stocks')
    op.drop_index('idx_screener_stocks_sector', table_name='screener_stocks')
    op.drop_index('idx_screener_stocks_industry', table_name='screener_stocks')
    op.drop_table('screener_stocks')
    op.drop_index('idx_mf_holdings_history_symbol', table_name='mf_holdings_history')
    op.drop_table('mf_holdings_history')
    op.drop_index('idx_magic_links_email', table_name='magic_links')
    op.drop_table('magic_links')
    # ### end Alembic commands ###
