"""add broker_connections background sync status columns

Revision ID: 35f10ea4dac3
Revises: b7cf5b79ce66
Create Date: 2026-08-03 09:19:30.164688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f10ea4dac3'
down_revision: Union[str, Sequence[str], None] = 'b7cf5b79ce66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_connections', sa.Column('sync_status', sa.String(length=20), server_default=sa.text("'idle'"), nullable=False))
    op.add_column('broker_connections', sa.Column('last_sync_summary', sa.JSON(), nullable=True))
    op.add_column('broker_connections', sa.Column('last_sync_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_connections', 'last_sync_error')
    op.drop_column('broker_connections', 'last_sync_summary')
    op.drop_column('broker_connections', 'sync_status')
    # ### end Alembic commands ###
