"""add broker_connections per-account api_key and api_secret_enc

Revision ID: 6c43f4a2d489
Revises: df6b59581b8b
Create Date: 2026-08-03 07:33:54.043531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c43f4a2d489'
down_revision: Union[str, Sequence[str], None] = 'df6b59581b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_connections', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.add_column('broker_connections', sa.Column('api_secret_enc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_connections', 'api_secret_enc')
    op.drop_column('broker_connections', 'api_key')
    # ### end Alembic commands ###
