"""add securities_bse and securities_sme tables

Revision ID: 903fbec42603
Revises: ec7850b73d2f
Create Date: 2026-09-14 08:48:36.897194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903fbec42603'
down_revision: Union[str, Sequence[str], None] = 'ec7850b73d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities_bse',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('securities_sme',
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('exchange', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities_sme')
    op.drop_table('securities_bse')
    # ### end Alembic commands ###
