"""add broker_connections pending_token_id for hdfc otp flow

Revision ID: 976659233671
Revises: 35f10ea4dac3
Create Date: 2026-08-03 23:00:31.771987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976659233671'
down_revision: Union[str, Sequence[str], None] = '35f10ea4dac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_connections', sa.Column('pending_token_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_connections', 'pending_token_id')
    # ### end Alembic commands ###
