"""add transactions external_ref for broker trade dedup

Revision ID: b7cf5b79ce66
Revises: 6c43f4a2d489
Create Date: 2026-08-03 08:46:31.717640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cf5b79ce66'
down_revision: Union[str, Sequence[str], None] = '6c43f4a2d489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_ref', sa.String(length=80), nullable=True))
    op.create_unique_constraint('uq_transactions_asset_external_ref', 'transactions', ['asset_id', 'external_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_asset_external_ref', 'transactions', type_='unique')
    op.drop_column('transactions', 'external_ref')
    # ### end Alembic commands ###
