"""add broker_connections table

Revision ID: df6b59581b8b
Revises: a7f2c1d09b34
Create Date: 2026-08-03 06:05:12.991690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6b59581b8b'
down_revision: Union[str, Sequence[str], None] = 'a7f2c1d09b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('token_obtained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'broker', name='uq_broker_connections_account_broker')
    )
    op.create_index('idx_broker_connections_profile', 'broker_connections', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_broker_connections_profile', table_name='broker_connections')
    op.drop_table('broker_connections')
    # ### end Alembic commands ###
